
name: test

on:
  workflow_dispatch:

  pull_request:
    branches: [ master ]
    
env:
  BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
  
jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: echo
        run: echo ${{ env.BRANCH_NAME }}
      - name: echo
        run: echo ${{ !startsWith( github.event.pull_request.head.ref, 'feature') }}
        
      - name: branch name check
        if: (${{ !startsWith(github.event.pull_request.head.ref, 'feature') }}) && (startsWith(${{ github.event.pull_request.head.ref }}, 'hotfix/') == false)
        run : exit 1

