
name: test

on:
  workflow_dispatch:

  pull_request:
    branches: [ master ]
    
env:
  BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
  
jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: echo1
        run: echo ${{ env.BRANCH_NAME }}
        
      - name: echo2
        run: echo ${{ !startsWith( env.BRANCH_NAME, 'hotfix') }}
        
      - name: echo3
        run: echo (${{ BRANCH_NAME }} != 'release')  }}
        
      - name: branch name check
        if: ${{ !startsWith(env.BRANCH_NAME, 'feature') }} && ${{ !startsWith(env.BRANCH_NAME, 'hotfix') }} && (${{ BRANCH_NAME }} != 'main') && (${{ BRANCH_NAME }} != 'cbt') && (${{ BRANCH_NAME }} != 'release')
        run : exit 1

